//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpadesGroceryShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        [Required]
        public int Emp_Id { get; set; }
        [Required]

        public string Emp_Name { get; set; }

        [Required]

        public string Emp_Nid { get; set; }
        [Required]

        public string Emp_Phone { get; set; }
        [Required]

        public string Emp_Email { get; set; }
        [Required]

        public string Emp_Salary { get; set; }

    }
}
