//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpadesGroceryShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Manager
    {
        [Required]
        [RegularExpression("^[a-zA-Z][a-zA-Z0-9]*[@][a-zA-Z]*[.][c][o][m]", ErrorMessage = "Invalid Email!")]

        public string Email { get; set; }
        [Required]
        [MinLength(4, ErrorMessage = "Password must be 4 or more characters")]

        public string Password { get; set; }
        public string LoginErrorMessage { get; set; }
    }
}
